WebApp/WebApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^order/', include('orders.urls', namespace='orders')),
]

WebApp/accounts/urls.py
from django.conf.urls import url
from . import views
#from django.contrib.auth.views import login, logout

urlpatterns = [
	url(r'^login/$', views.login_view, name='login_view'),
	#url(r'^auth/$', views.my_view, name='my_view'),
	url(r'^logout/$', views.logout_view, name='logout_view'),
	url(r'^register/$', views.register, name='register'),
	url(r'^profile/$', views.view_profile, name='view_profile'),
	url(r'^profile/edit/(?P<pk>\d+)/$', views.edit_profile, name='edit_profile'),
	url(r'^allusers/$', views.allusers, name='allusers'),
]

# {'template_name':'accounts/login.html'},
# {'template_name':'accounts/logout.html'}, 

WebApp/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^placeorder/$', views.placeorder, name='placeorder'),
    url(r'^listorders/$', views.listorders, name='listorders'),
    url(r'^order_history/$', views.order_history, name='order_history'),
]

WebApp/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
	ACCESS_OPTIONS = (
		('Admin', 'Admin'),
		('User', 'User'),
		)
	user = models.OneToOneField(User)
	access = models.CharField(max_length=10, choices=ACCESS_OPTIONS, default='User')
	contact_number = models.CharField(default=0, max_length=10)
	balance_amount = models.IntegerField(default=0)

	def __str__(self):
		return self.user.username

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

WebApp/orders/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

class Order(models.Model):
	TIME_OPTIONS = (
		('B', 'Breakfast'),
		('L', 'Lunch'),
		('D', 'Dinner'),
		)
	#STATUS_OPTIONS = (
	#	('O', 'Ordered'),
	#	('D', 'Delievered'),
	#	('C', 'Cancelled'),
	#	)
	user = models.ForeignKey(User)
	date = models.DateField(default=datetime.date.today)
	time = models.CharField(max_length=1, choices=TIME_OPTIONS)
	quantity = models.IntegerField(default=1)
	#status = models.CharField(max_length=1, default='O')	
	payable_amount = models.IntegerField(blank=True)

	def __str__(self):
		return self.id

class AddPrice(models.Model):
	cost_of_breakfast = models.IntegerField(default=45)
	cost_of_lunch = models.IntegerField(default=45)
	cost_of_dinner = models.IntegerField(default=45)

WebApp/accounts/forms.py
from django import forms
from django.forms import ModelForm
from accounts.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = {'username', 'first_name', 'last_name', 'email', 'password1', 'password2',}

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user

class EditProfileForm(UserChangeForm):
	class Meta:
		model = UserProfile
		fields = {'balance_amount', 'password', }

class LoginForm(forms.Form):
	username = forms.CharField(label='username', max_length=100)
	password = forms.CharField(widget=forms.PasswordInput())
	#access = forms.CharField(label='access', max_length=100)

WebApp/orders/forms.py
from django.forms import ModelForm
from orders.models import Order

class OrderForm(ModelForm):
	class Meta:
		model = Order
		fields = ['date', 'time', 'quantity', ]

WebApp/WebApp/views.py
from django.shortcuts import redirect

def login_redirect(request):
	return redirect('/account/login')

WebApp/accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm, LoginForm, EditProfileForm
from django.contrib.auth.decorators import login_required
from accounts.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from orders import views
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import UserChangeForm

def check_admin(user):
	return user.is_superuser

@user_passes_test(check_admin)
def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/order')

	else:
		form = RegistrationForm()

		args = {'form' : form}
		return render(request, 'accounts/reg_form.html', args)

def view_profile(request):
	args = {'user' : request.user}
	return render(request, 'accounts/profile.html', args)

@user_passes_test(check_admin)
def allusers(request):
	users = UserProfile.objects.all()
	args = {'users': users}
	return render(request, 'accounts/allusers.html', args)

@user_passes_test(check_admin)
def edit_profile(request, pk):
	k = UserProfile.objects.get(pk=pk)
	if request.method == 'POST':
		form = EditProfileForm(request.POST, instance=k.user)
		if form.is_valid():
			#cno = form.cleaned_data['contact_number']
			bamt = form.cleaned_data['balance_amount']
			form.save()
			#k.contact_number = cno
			k.balance_amount += bamt
			k.save()
			return redirect('/account/allusers')

	else:
		form = EditProfileForm(instance=k.user)
		args = {'form':form, 'user':k}
		return render(request, 'accounts/edit_profile.html', args)

def login_view(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			#access = form.cleaned_data['access']
			user = authenticate(request, username=username, password=password)
			#if (access == ''):
			#	print ("cannot get access value")
			if user is not None:
				login(request, user)
				k = UserProfile.objects.get(user=user)
				access = k.access 
				if access == 'User':
					return redirect('/order/placeorder')
				else:
					return redirect('/order/listorders')
			else:
				return HttpResponse("Invalid login essentials", {})

	else:
		form = LoginForm()

	return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return render(request, 'accounts/logout.html')

WebApp/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import OrderForm
from .models import Order, AddPrice
from django.utils import timezone
from accounts.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test

def check_admin(user):
	return user.is_superuser

def home(request):
	return render(request, 'orders/home.html')

def placeorder(request):
	if request.method == 'POST':
		form = OrderForm(request.POST)
		if form.is_valid():
			order = form.save(commit=False)
			order.user = request.user
			order.payable_amount = calculatePayment(order.quantity, order.time)
			updateBalance(request.user, order.payable_amount)
			order = form.save()
			return redirect('/order/listorders')
	else:
		form = OrderForm()
	return render(request, 'orders/placeorder.html', {'form': form})

@user_passes_test(check_admin)
def listorders(request):
	orders = Order.objects.all().order_by('-date')
	return render(request, 'orders/listorders.html', {'orders' : orders})

def calculatePayment(quantity, time):
	if time == 'B':
		k = AddPrice.objects.get(id=1)
		return quantity*k.cost_of_breakfast
	elif time == 'L':
		k = AddPrice.objects.get(id=1)
		return quantity*k.cost_of_lunch
	elif time == 'D':
		k = AddPrice.objects.get(id=1)
		return quantity*k.cost_of_dinner

def updateBalance(user, payment):
	k = UserProfile.objects.get(user=user)
	print(k)
	print (k.balance_amount)
	k.balance_amount -= payment
	k.save()

def order_history(request):
	orders = Order.objects.all().filter(user=request.user).order_by('-date')
	return render(request, 'orders/order_history.html', {'orders' : orders})

WebApp/accounts/templates/accounts/allusers.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<table style="width: 80%; border: 2px solid black">
				<th>
					<td>Contact Numbers</td>
					<td>Balance Amount</td>
				</th>	
				{% for u in users %}
				<tr>
					<td style="padding-left: 30%; padding-right: 10%; margin: 20px;"><a href="{% url 'accounts:edit_profile' pk=u.pk %}">{{u.contact_number}}</a></td>
					<td style="padding-left: 40%; padding-right: 5%; margin: 20px;">{{u.balance_amount}}</td>
				</tr>
		{% endfor %}
		</table>
	</div>
{% endblock %}

WebApp/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Submit</button>
			<br>
		</form>
	</div>
{% endblock %}

WebApp/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
{% if form.errors %}
	<p>Invalid username or password</p>
{% endif %}

<div class="container" style="width: 50%; height: 70%;">
<div class="jumbotron">
  	<h1 class="display-5">Login</h1>
  	<form action="" method="post">
  		{% csrf_token %}
    	<label for="username">Username : </label>
    	<input id="username" type="text" name="username" value=""><br>
    	<label for="password">Password : </label>
    	<input id="password" type="password" name="password" value=""><br>
    	<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>
</div>
{% endblock %}

WebApp/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="width: 50%; height: 70%;">
<div class="jumbotron">
  <h1 class="display-6">Logged out</h1>
</div>
</div>
{% endblock %}

WebApp/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<h1>Profile</h1>
		<p>Username : {{ user }}</p>
		<p>Email : {{ user.email }}</p>
		<p>Contact no. : {{ user.userprofile.contact_number }}</p>
		<p>Balance Amount : {{ user.userprofile.balance_amount }}</p>
{% endblock %}

WebApp/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="width: 70%; height: 70%;">
<div class="jumbotron">
  <h1 class="display-4">Register</h1>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>
</div>
{% endblock %}

WebApp/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css">

    <title>Hello</title>

  </head>
  <body>
    <br> 
  	<div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">TiffinBookingService</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          {% if user.is_authenticated %}
            {% if user.is_superuser %}
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
                <a class="nav-item nav-link" href="{% url 'orders:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'orders:listorders' %}">List Orders</a>
                <a class="nav-item nav-link" href="{% url 'accounts:allusers' %}">Users List</a>
                <!-- <a class="nav-item nav-link" href="{% url 'accounts:edit_profile' pk=user.pk %}">Edit Profile</a> -->
                <a class="nav-item nav-link" href="{% url 'accounts:logout_view' %}">Logout</a>
              </div>
            {% else %}
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'orders:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'accounts:view_profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'accounts:logout_view' %}">Logout</a>
              <a class="nav-item nav-link" href="{% url 'orders:placeorder' %}">Place Order</a>
             <!-- <a class="nav-item nav-link" href="{% url 'orders:listorders' %}">List Orders</a> -->
              <a class="nav-item nav-link" href="{% url 'orders:order_history' %}">Order History</a>
            </div>
            {% endif %}
          {% else %}
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'accounts:login_view' %}">Login</a>
             <!--  <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a> -->
            </div>
        {% endif %}
  </div>
</nav>
    </div>
    <br>
  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

WebApp/orders/templates/orders/home.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<h1>Home</h1>
	</div>
{% endblock %}

WebApp/orders/templates/orders/listorders.html
{% extends 'base.html' %}

{% block content %}

{% for odr in orders %}

	<table>
	<tr>
	<td style="padding: 15px">User : {{ odr.user }}</td>
	<td style="padding: 15px">Date : {{ odr.date }}</td>
	<td style="padding: 15px">Time : {% if odr.time == 'B' %} Breakfast {% elif odr.time == 'L' %} Lunch {% elif odr.time == 'D' %} Dinner {% endif %}</td>
	<td style="padding: 15px">Quantity : {{ odr.quantity }}</td>
	<td style="padding: 15px">Payment : {{ odr.payable_amount }}</td>
	</table>

{% endfor %}

{% endblock %}

WebApp/orders/templates/orders/order_history.html
{% extends 'base.html' %}

{% block content %}

{% for odr in orders %}

	<table>
	<tr>
	<td style="padding: 15px">User : {{ odr.user }}</td>
	<td style="padding: 15px">Date : {{ odr.date }}</td>
	<td style="padding: 15px">Time : {% if odr.time == 'B' %} Breakfast {% elif odr.time == 'L' %} Lunch {% elif odr.time == 'D' %} Dinner {% endif %}</td>
	<td style="padding: 15px">Quantity : {{ odr.quantity }}</td>
	<td style="padding: 15px">Payment : {{ odr.payable_amount }}</td>
	</table>

{% endfor %}

{% endblock %}

WebApp/orders/templates/orders/placeorder.html
{% extends 'base.html' %}

{% block content %}

<h2>Place Order</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Save</button>
</form>
{% endblock %}